##Docker image for HIPE dataset.
version: '1.0'
services:
  neo4j:
    image: neo4j:4.4-community
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
      - ./plugins:/plugins
      - ./conf:/conf
    environment:
      - NEO4J_AUTH=neo4j/password
    restart: always
