version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    networks:
      - webnet
    extra_hosts:
      - "demo.test:127.0.0.1"

networks:
  webnet:
