version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./certs:/etc/ssl/certs
    environment:
      APACHE_LOG_DIR: /var/log/apache2
